### ISSUE TITLE
Would like song length in list 

### ISSUE THREAD

**Issue by MFornander** [Phrogz/rb3jay#4]
Awesome work :+1: 
it would be cool if the song length such as 1:12:10 or 3:21 could be (optionally?) shown in the lists.

**Comment by Phrogz** [comment]
Every list, or just the leftmost song searcher? I'd also like to show your own song rating, and (in "up next") who added the song. However, without a generic "column chooser", I'm worried that we'll run out of space too fast. It's already too tight unless you full-screen the app. :/

**Comment by Phrogz** [comment]
Decided to just add it for now. It's a good choice. :+1:
